services:
  type-server:
    image: "as3305100/type-app:latest"
    deploy:
      replicas: 2
      update_config:
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 1
        order: start-first
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--spider",
          "http://localhost:3000/health",
        ]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    networks:
      - typeapp-network

networks:
  typeapp-network:
