
name: Type-app

on: 
 push:
   branches: ["main"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
    # this permissions contents : write means it allows to write in the repository
       contents: write 
    env:
      IMAGE_NAME: as3305100/type-app
      IMAGE_TAG: build-${{github.run_number}}
     
     steps: 
       - name: checkout the source code
         uses: actions/checkout@v4
         with: 
          persist-credentials: true
       - name: Build docker image
         run: docker build -t ${{env.IMAGE_NAME}}:${{env.IMAGE_TAG}} --platform linux/amd64 .
       - name: Login into docker hub
         uses: docker/login-action@v3
         with: 
           username: ${{secrets.DOCKERHUB_USERNAME}}
           password: ${{secrets.DOCKERHUB_PASSWORD}}
       - name: Push docker image to docker hub
         run: docker push ${{env.IMAGE_NAME}}:${{env.IMAGE_TAG}}
       - name: update compose yaml
         uses: fjogeleit/yaml-update-action@v0.16.1
         with:
          valueFile: compose.yaml
          propertyPath: 'sevices["type-server"].image'
          value: ${{env.IMAGE_NAME}}:${{env.IMAGE_TAG}}
          commitChange: false
       - name: commit the compose.yaml file change in github
         run: |
           git config user.name github-actions
           git config user.email github-action@github.com
           git add .
           git commit -m "bump the large version ${{env.IMAGE_TAG}}"
           git push
